package org.cyk.system.iesaschool.model;

public interface IesaConstant {

	String EVALUATION_TYPE_TEST1 = "Test1";
	String EVALUATION_TYPE_TEST2 = "Test2";
	String EVALUATION_TYPE_EXAM = "Exam";
	
	String LEVEL_NAME_CODE_PK = "PK";
	String LEVEL_NAME_CODE_K1 = "K1";
	String LEVEL_NAME_CODE_K2 = "K2";
	String LEVEL_NAME_CODE_K3 = "K3";
	String LEVEL_NAME_CODE_G1 = "G1";
	String LEVEL_NAME_CODE_G2 = "G2";
	String LEVEL_NAME_CODE_G3 = "G3";
	String LEVEL_NAME_CODE_G4 = "G4";
	String LEVEL_NAME_CODE_G5 = "G5";
	String LEVEL_NAME_CODE_G6 = "G6";
	String LEVEL_NAME_CODE_G7 = "G7";
	String LEVEL_NAME_CODE_G8 = "G8";
	String LEVEL_NAME_CODE_G9 = "G9";
	String LEVEL_NAME_CODE_G10 = "G10";
	String LEVEL_NAME_CODE_G11 = "G11";
	String LEVEL_NAME_CODE_G12 = "G12";
	
	String REPORT_CYK_GLOBAL_RANKABLE = "CYK_GLOBAL_RANKABLE";
	
	String MERIC_COLLECTION_G1_G6_STUDENT_BEHAVIOUR = "BSWHG1G6";
	String MERIC_COLLECTION_G7_G12_STUDENT_BEHAVIOUR = "BSWHG7G12";
	
	String MERIC_COLLECTION_PK_STUDENT_EXPRESSIVE_LANGUAGE = "MCPKSEL";
	String MERIC_COLLECTION_PK_STUDENT_RECEPTIVE_LANGUAGE = "MCPKSRL";
	String MERIC_COLLECTION_PK_STUDENT_READING_READNESS = "MCPKSRR";
	String MERIC_COLLECTION_PK_STUDENT_NUMERACY_DEVELOPMENT = "MCPKSND";
	String MERIC_COLLECTION_PK_STUDENT_ARTS_MUSIC = "MCPKSAM";
	String MERIC_COLLECTION_PK_STUDENT_SOCIAL_EMOTIONAL_DEVELOPMENT = "MCPKSSED";
	String MERIC_COLLECTION_PK_STUDENT_GROSS_MOTOR_SKILLS = "MCPKSGMS";
	String MERIC_COLLECTION_PK_STUDENT_FINE_MOTOR_SKILLS = "MCPKSFMS";

}
