package org.cyk.system.iesaschool.model;

import java.io.Serializable;

public interface IesaConstant {
	
	String IESA = "IESA";
	
	String SUBJECT_MATHEMATICS_CODE = "S01";
	String SUBJECT_GRAMMAR_CODE = "S02";
	String SUBJECT_READING_COMPREHENSION_CODE = "S03";
	String SUBJECT_HANDWRITING_CODE = "S04";
	String SUBJECT_SPELLING_CODE = "S05";
	String SUBJECT_PHONICS_CODE = "S06";
	String SUBJECT_CREATIVE_WRITING_CODE = "S07";
	String SUBJECT_MORAL_EDUCATION_CODE = "S08";
	String SUBJECT_SOCIAL_STUDIES_CODE = "S09";
	String SUBJECT_SCIENCE_CODE = "S10";
	String SUBJECT_FRENCH_CODE = "S11";
	String SUBJECT_ART_CRAFT_CODE = "S12";
	String SUBJECT_MUSIC_CODE = "S13";
	String SUBJECT_ICT_COMPUTER_CODE = "S14";
	String SUBJECT_PHYSICAL_EDUCATION_CODE = "S15";
	String SUBJECT_LITERATURE_CODE = "S16";
	String SUBJECT_COMPREHENSION_CODE = "S17";
	String SUBJECT_HISTORY_CODE = "S18";
	String SUBJECT_ENGLISH_LANGUAGE_CODE = "S19";
	String SUBJECT_LITERATURE_IN_ENGLISH_CODE = "S20";
	String SUBJECT_GEOGRAPHY_CODE = "S21";
	String SUBJECT_PHYSICS_CODE = "S22";
	String SUBJECT_CHEMISTRY_CODE = "S23";
	String SUBJECT_BIOLOGY_CODE = "S24";
	String SUBJECT_SPANISH_CODE = "S25";
	String SUBJECT_ENGLISH_LITERATURE_CODE = "S26";
	String SUBJECT_CHINESE_MANDARIN_CODE = "S27";
	String SUBJECT_ACCOUNTING_CODE = "S28";
	String SUBJECT_BUSINESS_STUDIES_CODE = "S29";
	String SUBJECT_ECONOMICS_CODE = "S30";
	String SUBJECT_ADVANCED_MATHEMATICS_CODE = "S31";
	String SUBJECT_CORE_MATHEMATICS_CODE = "S32";
	String SUBJECT_ART_DESIGN_CODE = "S33";
	String SUBJECT_DEVELOPMENT_STUDIES_CODE = "S34";
	String SUBJECT_ENVIRONMENTAL_MANAGEMENT_CODE = "S35";
	String SUBJECT_SOCIOLOGY_CODE = "S36";
	String SUBJECT_LAW_CODE = "S37";
	
	String EVALUATION_TYPE_TEST1 = "Test1";
	String EVALUATION_TYPE_TEST2 = "Test2";
	String EVALUATION_TYPE_EXAM = "Exam";
		
	String REPORT_CYK_GLOBAL_RANKABLE = "CYK_GLOBAL_RANKABLE";
	
	/**/
	
	public static class Code implements Serializable {
		private static final long serialVersionUID = 1L;

		
		
		
	}

}
