package org.cyk.system.iesaschool.model;

public interface IesaConstant {
	
	String SUBJECT_MATHEMATICS_CODE = "S01";
	String SUBJECT_GRAMMAR_CODE = "S02";
	String SUBJECT_READING_COMPREHENSION_CODE = "S03";
	String SUBJECT_HANDWRITING_CODE = "S04";
	String SUBJECT_SPELLING_CODE = "S05";
	String SUBJECT_PHONICS_CODE = "S06";
	String SUBJECT_CREATIVE_WRITING_CODE = "S07";
	String SUBJECT_MORAL_EDUCATION_CODE = "S08";
	String SUBJECT_SOCIAL_STUDIES_CODE = "S09";
	String SUBJECT_SCIENCE_CODE = "S10";
	String SUBJECT_FRENCH_CODE = "S11";
	String SUBJECT_ART_CRAFT_CODE = "S12";
	String SUBJECT_MUSIC_CODE = "S13";
	String SUBJECT_ICT_COMPUTER_CODE = "S14";
	String SUBJECT_PHYSICAL_EDUCATION_CODE = "S15";
	String SUBJECT_LITERATURE_CODE = "S16";
	String SUBJECT_COMPREHENSION_CODE = "S17";
	String SUBJECT_HISTORY_CODE = "S18";
	String SUBJECT_ENGLISH_LANGUAGE_CODE = "S19";
	String SUBJECT_LITERATURE_IN_ENGLISH_CODE = "S20";
	String SUBJECT_GEOGRAPHY_CODE = "S21";
	String SUBJECT_PHYSICS_CODE = "S22";
	String SUBJECT_CHEMISTRY_CODE = "S23";
	String SUBJECT_BIOLOGY_CODE = "S24";
	String SUBJECT_SPANISH_CODE = "S25";
	String SUBJECT_ENGLISH_LITERATURE_CODE = "S26";
	String SUBJECT_CHINESE_MANDARIN_CODE = "S27";
	String SUBJECT_ACCOUNTING_CODE = "S28";
	String SUBJECT_BUSINESS_STUDIES_CODE = "S29";
	String SUBJECT_ECONOMICS_CODE = "S30";
	String SUBJECT_ADVANCED_MATHEMATICS_CODE = "S31";
	String SUBJECT_CORE_MATHEMATICS_CODE = "S32";
	String SUBJECT_ART_DESIGN_CODE = "S33";
	String SUBJECT_DEVELOPMENT_STUDIES_CODE = "S34";
	String SUBJECT_ENVIRONMENTAL_MANAGEMENT_CODE = "S35";
	String SUBJECT_SOCIOLOGY_CODE = "S36";
	String SUBJECT_LAW_CODE = "S37";
	
	String EVALUATION_TYPE_TEST1 = "Test1";
	String EVALUATION_TYPE_TEST2 = "Test2";
	String EVALUATION_TYPE_EXAM = "Exam";
	
	String LEVEL_NAME_CODE_PK = "PK";
	String LEVEL_NAME_CODE_K1 = "K1";
	String LEVEL_NAME_CODE_K2 = "K2";
	String LEVEL_NAME_CODE_K3 = "K3";
	String LEVEL_NAME_CODE_G1 = "G1";
	String LEVEL_NAME_CODE_G2 = "G2";
	String LEVEL_NAME_CODE_G3 = "G3";
	String LEVEL_NAME_CODE_G4 = "G4";
	String LEVEL_NAME_CODE_G5 = "G5";
	String LEVEL_NAME_CODE_G6 = "G6";
	String LEVEL_NAME_CODE_G7 = "G7";
	String LEVEL_NAME_CODE_G8 = "G8";
	String LEVEL_NAME_CODE_G9 = "G9";
	String LEVEL_NAME_CODE_G10 = "G10";
	String LEVEL_NAME_CODE_G11 = "G11";
	String LEVEL_NAME_CODE_G12 = "G12";
	
	String REPORT_CYK_GLOBAL_RANKABLE = "CYK_GLOBAL_RANKABLE";
	
	String MERIC_COLLECTION_G1_G6_STUDENT_BEHAVIOUR = "BSWHG1G6";
	String MERIC_COLLECTION_G7_G12_STUDENT_BEHAVIOUR = "BSWHG7G12";
	
	String MERIC_COLLECTION_PK_STUDENT_EXPRESSIVE_LANGUAGE = "MCPKSEL";
	String MERIC_COLLECTION_PK_STUDENT_RECEPTIVE_LANGUAGE = "MCPKSRL";
	String MERIC_COLLECTION_PK_STUDENT_READING_READNESS = "MCPKSRR";
	String MERIC_COLLECTION_PK_STUDENT_NUMERACY_DEVELOPMENT = "MCPKSND";
	String MERIC_COLLECTION_PK_STUDENT_ARTS_MUSIC = "MCPKSAM";
	String MERIC_COLLECTION_PK_STUDENT_SOCIAL_EMOTIONAL_DEVELOPMENT = "MCPKSSED";
	String MERIC_COLLECTION_PK_STUDENT_GROSS_MOTOR_SKILLS = "MCPKSGMS";
	String MERIC_COLLECTION_PK_STUDENT_FINE_MOTOR_SKILLS = "MCPKSFMS";
	
	String MERIC_COLLECTION_K1_STUDENT_ENGLISH_LANGUAGE_ARTS_READING = "MCK1SELAR";
	String MERIC_COLLECTION_K1_STUDENT_COMMUNICATION_SKILLS = "MCK1SCS";
	String MERIC_COLLECTION_K1_STUDENT_SCIENCE = "MCK1SS";
	String MERIC_COLLECTION_K1_STUDENT_SOCIAL_STUDIES = "MCK1SSS";
	String MERIC_COLLECTION_K1_STUDENT_MATHEMATICS = "MCK1SM";
	String MERIC_COLLECTION_K1_STUDENT_WORK_HABITS = "MCK1SWH";
	String MERIC_COLLECTION_K1_STUDENT_SOCIAL_SKILLS = "MCK1SSSK";
	
	String MERIC_COLLECTION_K2_K3_STUDENT_READING_READINESS = "MCK2K3SRR";
	String MERIC_COLLECTION_K2_K3_STUDENT_READING = "MCK2K3SR";
	String MERIC_COLLECTION_K2_K3_STUDENT_WRITING = "MCK2K3SW";
	String MERIC_COLLECTION_K2_K3_STUDENT_LISTENING_SPEAKING_VIEWING = "MCK2K3SLSV";
	String MERIC_COLLECTION_K2_K3_STUDENT_ALPHABET_IDENTIFICATION = "MCK2K3SAI";
	String MERIC_COLLECTION_K2_K3_STUDENT_MATHEMATICS = "MCK2K3SM";
	String MERIC_COLLECTION_K2_K3_STUDENT_SCIENCE_SOCIAL_STUDIES_MORAL_EDUCATION = "MCK2K3SSSSME";
	String MERIC_COLLECTION_K2_K3_STUDENT_ART_CRAFT = "MCK2K3SAC";
	String MERIC_COLLECTION_K2_K3_STUDENT_MUSIC = "MCK2K3SMM";
	String MERIC_COLLECTION_K2_K3_STUDENT_PHYSICAL_EDUCATION = "MCK2K3SPE";
	String MERIC_COLLECTION_K2_K3_STUDENT_WORK_BEHAVIOUR_HABITS = "MCK2K3SWBH";
	
	String ROLE_TEACHER_CODE = "TEACHER";

}
